name = "nxv-router"
account_id = "$yourAccountId"
type = "webpack"
workers_dev = true

[env.production]
# The ID of the domain to deploying to
zone_id = "$yourZoneId"

# The route pattern your Workers application will be served at
routes = [
  "ngxv.org/",
  "ngxv.org/blog",
  "ngxv.org/blog/",
  "ngxv.org/blog/entry*",
  "ngxv.org/blog/tag*",
  "ngxv.org/blog/index.html",
  "ngxv.org/home",
  "ngxv.org/home/",
  "ngxv.org/home/index.html",
  "ngxv.org/index.html",
]
