language: "java"
os: "linux"
dist: "jammy"
jdk: "openjdk11"
cache:
  directories:
    - "$HOME/.deno"
    - "$HOME/.dart-sass"
    - "$HOME/.cache/deno"
branches:
  only:
    - "/^feature\/.*$/"
    - "main"
before_install:
  - "pwd"
  - "echo \"$TRAVIS_BRANCH\""
install: "./script/travis-install-dependencies"
script: "./script/travis-build"

