#!/bin/sh
rm -rf build
npx parcel build src/app/index.html --out-dir build/dist &
npx parcel build src/generator/generator.jsx --target node --out-dir build/generator &
wait
NODE_ENV='production' node build/generator/generator.js
rm -rf dist && cp -r build/dist dist
