#!/bin/bash

set -e

# Prepare branch for build
git checkout main
git checkout -b build

# Build website
script/build

# Commit build and push to github page
git add dist
git commit -m "Build nxv page at `date`"
git -C ../.. subtree split --prefix modules/web/dist -b gh-pages
git push -f origin gh-pages:gh-pages

# Clean up
git checkout main
git branch -D gh-pages
git branch -D build
git gc
