#!/usr/bin/env bash

set -e
set -o pipefail
set -v

SCRIPT_DIRECTORY="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

source "$SCRIPT_DIRECTORY/utilities"

PROJECT_DIRECTORY="$( absolute_path "${SCRIPT_DIRECTORY}/.." )"
WEB_DIRECTORY="${PROJECT_DIRECTORY}/web"
BUILD_DIRECTORY="${WEB_DIRECTORY}/build"

CACHE_DIRECTORY="${PROJECT_DIRECTORY}/.cache"
DENO_DIRECTORY="${CACHE_DIRECTORY}/deno"

# Client up build directory.
rm -rf "${BUILD_DIRECTORY}"
mkdir -p "${BUILD_DIRECTORY}"

# bundle the app to index.js.
DENO_DIR="${DENO_DIRECTORY}" deno run \
    --config "${PROJECT_DIRECTORY}/deno.jsonc" \
    --allow-read \
    --allow-run \
    --allow-env \
    --allow-write \
    "${WEB_DIRECTORY}/bundler/bundler.js" \
    --import-map "${PROJECT_DIRECTORY}/import-map.json" \
    --entrypoint "${WEB_DIRECTORY}/app/index.js" \
    --out-file "${WEB_DIRECTORY}/build/dist/index.js"

# bundle worker.js
DENO_DIR="${DENO_DIRECTORY}" deno run \
    --config "${PROJECT_DIRECTORY}/deno.jsonc" \
    --allow-read \
    --allow-run \
    --allow-env \
    --allow-write \
    "${WEB_DIRECTORY}/bundler/bundler.js" \
    --import-map "${PROJECT_DIRECTORY}/import-map.json" \
    --entrypoint "${WEB_DIRECTORY}/app/worker.js" \
    --out-file "${WEB_DIRECTORY}/build/dist/worker.js"

# download purecss
mkdir -p "${CACHE_DIRECTORY}/deps/purecss/2.1.0"
download \
    "8c01fbca2681ae46e5a6c626c236734cc7fea87785b611554fc818ece43c08ac" \
    "https://cdn.jsdelivr.net/npm/purecss@2.1.0/build/base-min.css" \
    "${CACHE_DIRECTORY}/deps/purecss/2.1.0/base-min.scss"
download \
    "dbb583ba6e838e6c22199e69bcae90af3ea735f959df70d97bc792bdeaf72285" \
    "https://cdn.jsdelivr.net/npm/purecss@2.1.0/build/grids-min.css" \
    "${CACHE_DIRECTORY}/deps/purecss/2.1.0/grids-min.scss"
download \
    "2131b61e813b7ce13fe5ab44c2a1bd25ab937f6eb4b5343584e22c981d262227" \
    "https://cdn.jsdelivr.net/npm/purecss@2.1.0/build/grids-responsive-min.css" \
    "${CACHE_DIRECTORY}/deps/purecss/2.1.0/grids-responsive-min.scss"
# bundle css to index.css.
sass --style compressed "$WEB_DIRECTORY/app/index.scss" "$WEB_DIRECTORY/build/dist/index.css"

# copy static content.
cp "$WEB_DIRECTORY/app/favicon.ico" "$WEB_DIRECTORY/build/dist/"
cp "$WEB_DIRECTORY/app/manifest.webmanifest" "$WEB_DIRECTORY/build/dist/"
cp "$WEB_DIRECTORY/app/index.html" "$WEB_DIRECTORY/build/dist/"
cp "$WEB_DIRECTORY/content/static/CNAME" "$WEB_DIRECTORY/build/dist/"
cp "$WEB_DIRECTORY/content/static/robots.txt" "$WEB_DIRECTORY/build/dist/"

# generate site from content.
DENO_DIR="${DENO_DIRECTORY}" deno run \
    --config "$PROJECT_DIRECTORY/deno.jsonc" \
    --allow-read \
    --allow-write \
    --allow-env \
    "$WEB_DIRECTORY/generator/generator.js"
