#!/bin/bash

set -e

SCRIPT_DIRECTORY="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

deno lint --config "$SCRIPT_DIRECTORY/../deno.json"
deno fmt --config "$SCRIPT_DIRECTORY/../deno.json"
