#!/usr/bin/env bash

set -e
set -o pipefail

SCRIPT_DIRECTORY="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

# Prepare branch for build
git checkout trunk
# Suppress error if branch doesn't exist
git branch -D build || true
git checkout -b build

# Build website
"$SCRIPT_DIRECTORY/build-web-prod"

# Commit build and push to github page
git add web/dist
git commit -m "Build nxv page at `date`"
git subtree split --prefix web/dist -b gh-pages
git push -f origin gh-pages:gh-pages

# Clean up
git checkout trunk
git branch -D gh-pages
git branch -D build
git gc
