#!/bin/bash
set -e

SCRIPT_DIRECTORY="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

# Environment variables
PROJECT_DIRECTORY="$SCRIPT_DIRECTORY/.."
DEV_SERVER_DIRECTORY="$PROJECT_DIRECTORY/dev-server"

# go to project directory.
pushd "$PROJECT_DIRECTORY"
deno run \
    --config "$PROJECT_DIRECTORY/deno.json" \
    --import-map "$PROJECT_DIRECTORY/import_map.json" \
    --lock lock.json \
    --watch \
    --allow-net \
    --allow-read \
    "$DEV_SERVER_DIRECTORY/server.js"
# back to previous directory after done.
popd

