#!/usr/bin/env bash

set -e
set -o pipefail

SCRIPT_DIRECTORY="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

source "$SCRIPT_DIRECTORY/utilities"

# Environment variables
PROJECT_DIRECTORY="$( absolute_path "${SCRIPT_DIRECTORY}/.." )"
WEB_DIRECTORY="$PROJECT_DIRECTORY/web"

CACHE_DIRECTORY="${PROJECT_DIRECTORY}/.cache"
DENO_DIRECTORY="${CACHE_DIRECTORY}/deno"

# We could not do type check because of `vendor/preact/hooks/internal.d.ts`.
DENO_DIR="${DENO_DIRECTORY}" deno test \
    --config "$PROJECT_DIRECTORY/deno.jsonc" \
    --allow-env \
    --no-check \
    "$WEB_DIRECTORY/test/"
