#!/bin/bash

# stop when error.
set -e
# print command.
set -v

SCRIPT_DIRECTORY="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

source "$SCRIPT_DIRECTORY/utilities"

LOCAL_BIN="${HOME}/.local/bin"
mkdir -p "${LOCAL_BIN}"

# install deno
export DENO_INSTALL="$HOME/.deno"
curl -fsSL https://deno.land/x/install/install.sh | sh
ln -s "${DENO_INSTALL}/bin/deno" "${LOCAL_BIN}/deno"

# install dart-sass
mkdir -p "$HOME/.dart-sass"
download \
    "36b3f8028c443317ee115464b5720ed4abe9ca8a6f86b2a579150ce78589f2af" \
    "https://github.com/sass/dart-sass/releases/download/1.54.4/dart-sass-1.54.4-linux-x64.tar.gz" \
    "$HOME/.dart-sass/dart-sass.tar.gz"
tar xvzf "$HOME/.dart-sass/dart-sass.tar.gz" -C "$HOME/.dart-sass"
ln -s "${HOME}/.dart-sass/dart-sass/sass" "${LOCAL_BIN}/sass"

