#!/bin/bash

# Download a file from URL and verify downloaded file with SHA256.
# If the file existed, verify it with SHA256. If the hash does not match, try
# to download the file from given URL.
# Pamameters:
#   $1: SHA256 hash.
#   $2: URL.
#   $3: Output.
download() {
  local hash="$1"
  local url="$2"
  local output="$3"
  local sha256="$hash  $output"
  if ! echo "$sha256" | shasum -s -c; then
    curl -L "$url" -o "$output"
    echo "$sha256" | shasum -s -c
  fi
}
