# The public IP that relayd will listen on.
public_ipv4 = "<ip-address"

httpd_http = "8080"
table <local> {
  "127.0.0.1"
}

# Define HTTP protocol for relaying, all packages matche this protocol will
# be relayed to the defined destination.
http protocol "www" {
  # ngxv.org
  match request header "Host" value "ngxv.org" forward to <local>
  match request header "Host" value "www.ngxv.org" forward to <local>

  # Because relayd serve as a reverse proxy, we need to add these headers to
  # help httpd recognize source address.
  match request header set "X-Forwarded-Proto"  value "http"
  match request header set "X-Forwarded-Host"   value "$HOST"
  match request header set "X-Forwarded-Port"   value "$SERVER_PORT"
  match request header set "X-Forwarded-For"    value "$REMOTE_ADDR"
  match request header set "X-Forwarded-By"     value "$SERVER_ADDR:$SERVER_PORT"
}

# Relay HTTP connection to httpd
relay "http" {
  listen on $public_ipv4 port 80
  protocol "www"
  forward to <local> port $httpd_http
}

