name: "build"
on: [ "push" ]
jobs:
  build-ngxv:
    name: "Build ngxv.org"
    runs-on: "ubuntu-22.04"
    steps:
      - uses: "actions/checkout@v3"
      - run: "bash ./script/travis-install-dependencies"
      - run: "bash ./script/build-web-prod"
